-- CREATE WAREHOUSE, DATABASES AND SCHEMAS **********************************************************************************************
CREATE WAREHOUSE IF NOT EXISTS HOUSEPRICEPROJECT_WH1; -- MODIFICARE .............................
CREATE DATABASE IF NOT EXISTS HOUSING_PRICE_PROJECT;
CREATE SCHEMA IF NOT EXISTS HOUSING_PRICE_PROJECT.STAGING_LAYER;
CREATE SCHEMA IF NOT EXISTS HOUSING_PRICE_PROJECT.CLEANING_LAYER;
CREATE SCHEMA IF NOT EXISTS HOUSING_PRICE_PROJECT.ML_LAYER;

USE WAREHOUSE HOUSEPRICEPROJECT_WH1; 
USE DATABASE HOUSING_PRICE_PROJECT;

-- CREATE THE STAGE TO STORE THE PYTHON CODES *********************************************************************************************
CREATE STAGE IF NOT EXISTS HOUSING_PRICE_PROJECT.PUBLIC.PROJECT_CODE;


-- CREATE THE STAGE TO STORE ML JOB ARTIFACTS **********************************************************************************************
CREATE STAGE IF NOT EXISTS HOUSING_PRICE_PROJECT.ML_LAYER.MLJOBS_STAGE;


-- CREATE THE COMPUTE POOL FOR ML JOB ********************************************************************************************** 
CREATE COMPUTE POOL IF NOT EXISTS ML_JOB_COMPUTERPOOL
    MIN_NODES = 1
    MAX_NODES = 50
    INSTANCE_FAMILY = CPU_X64_M;