-- CREATE THE STORED PROCEDURE FOR CREATING THE QUALITY CHECK REPORT **********************************************************************************************
CREATE OR REPLACE PROCEDURE HOUSING_PRICE_PROJECT.STAGING_LAYER.QUALITY_CHECK_REPORT_PROC()
RETURNS BOOLEAN
LANGUAGE PYTHON
RUNTIME_VERSION='3.12'
PACKAGES=('snowflake-snowpark-python')
IMPORTS=('@HOUSING_PRICE_PROJECT.PUBLIC.PROJECT_CODE/data_quality_report.py')
HANDLER='data_quality_report.main';


-- CREATE THE TASK TO AUTOMATIZE THE QUALITY CHECK REPORT BUILDING **********************************************************************************************
CREATE OR REPLACE TASK HOUSING_PRICE_PROJECT.PUBLIC.QUALITYCHECK_REPORT_TASK
WAREHOUSE = HOUSEPRICEPROJECT_WH1
SCHEDULE ='1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA(
    'HOUSING_PRICE_PROJECT.STAGING_LAYER.RAWDATA_STREAM'
)
AS
CALL HOUSING_PRICE_PROJECT.STAGING_LAYER.QUALITY_CHECK_REPORT_PROC();