-- CREATE EMPTY CLEAN_DATA TABLE ***********************************************
CREATE TABLE IF NOT EXISTS HOUSING_PRICE_PROJECT.CLEANING_LAYER.CLEAN_DATA
AS
SELECT * FROM HOUSING_PRICE_PROJECT.STAGING_LAYER.RAW_DATA LIMIT 0;


-- CREATE THE STREAM OVER CLEAN_DATA TABLE ************************************************************************************************************************
CREATE OR REPLACE STREAM HOUSING_PRICE_PROJECT.CLEANING_LAYER.CLEANDATA_STREAM 
ON TABLE HOUSING_PRICE_PROJECT.CLEANING_LAYER.CLEAN_DATA; 


-- CREATE THE STORED PROCEDURE FOR UPLOADING THE CLEAN DATA INTO THE TAB *********************************************************************************************
CREATE OR REPLACE PROCEDURE HOUSING_PRICE_PROJECT.CLEANING_LAYER.CLEAN_DATA_PROC(max_nulls INT)
RETURNS STRING
LANGUAGE PYTHON
RUNTIME_VERSION='3.12'
PACKAGES=('snowflake-snowpark-python')
IMPORTS=('@HOUSING_PRICE_PROJECT.PUBLIC.PROJECT_CODE/clean_data.py')
HANDLER='clean_data.main';


-- CREATE THE TASK TO RUN THE STORED PROCEDURE ***********************************************************************************************************************
CREATE OR REPLACE TASK HOUSING_PRICE_PROJECT.PUBLIC.CLEAN_DATA_TASK
WAREHOUSE = housepriceproject_wh1
AFTER HOUSING_PRICE_PROJECT.PUBLIC.QUALITYCHECK_REPORT_TASK
AS
CALL HOUSING_PRICE_PROJECT.CLEANING_LAYER.CLEAN_DATA_PROC(10);