-- CREATE THE REQUIRED TABLES ********************************************************************************
CREATE TABLE IF NOT EXISTS HOUSING_PRICE_PROJECT.ML_LAYER.TRAIN_SET
AS
SELECT * EXCLUDE (BHK, 
BATHROOMS, 
BUILT_UP_AREA, 
PROPERTY_ID, 
PRICE_CATEGORY, 
SOURCE_FILE
) 
FROM HOUSING_PRICE_PROJECT.CLEANING_LAYER.CLEAN_DATA LIMIT 0;

CREATE TABLE IF NOT EXISTS HOUSING_PRICE_PROJECT.ML_LAYER.TEST_SET
AS
SELECT * EXCLUDE (BHK, 
BATHROOMS, 
BUILT_UP_AREA, 
PROPERTY_ID, 
PRICE_CATEGORY, 
SOURCE_FILE
) 
FROM HOUSING_PRICE_PROJECT.CLEANING_LAYER.CLEAN_DATA LIMIT 0;



-- CREATE THE STORED PROCEDURE  **********************************************************************************************
CREATE OR REPLACE PROCEDURE HOUSING_PRICE_PROJECT.ML_LAYER.TRAINTEST_SPLIT_PROC(testset_cap INT) -- max number of rows in TEST_SET table (use 5000)
RETURNS BOOLEAN
LANGUAGE PYTHON
RUNTIME_VERSION='3.12'
PACKAGES=('snowflake-snowpark-python')
IMPORTS=('@HOUSING_PRICE_PROJECT.PUBLIC.PROJECT_CODE/ML_CODE/ML_traintest_split.py')
HANDLER='ML_traintest_split.main';



-- CREATE THE TASK TO RUN THE STORED PROCEDURE  ******************************************************************************************************
CREATE OR REPLACE TASK HOUSING_PRICE_PROJECT.PUBLIC.TRAINTEST_SPLIT_TASK
WAREHOUSE = HOUSEPRICEPROJECT_WH1
AFTER HOUSING_PRICE_PROJECT.PUBLIC.CLEAN_DATA_TASK
AS 
CALL HOUSING_PRICE_PROJECT.ML_LAYER.TRAINTEST_SPLIT_PROC(5000);