-- CREATE THE STORED PROCEDURE  **********************************************************************************************
CREATE OR REPLACE PROCEDURE HOUSING_PRICE_PROJECT.ML_LAYER.PREPROCESSING_PROC()
RETURNS BOOLEAN
LANGUAGE PYTHON
RUNTIME_VERSION='3.12'
PACKAGES = (
    'snowflake-snowpark-python',
    'snowflake-ml-python == 1.51.0'
)
IMPORTS=('@HOUSING_PRICE_PROJECT.PUBLIC.PROJECT_CODE/ML_CODE/ML_preproc.py')
HANDLER='ML_preproc.main';




-- CREATE THE TASK TO RUN THE STORED PROCEDURE ******************************************************************************************************
CREATE OR REPLACE TASK HOUSING_PRICE_PROJECT.PUBLIC.PREPROCESSING_TASK
WAREHOUSE = HOUSEPRICEPROJECT_WH1
AFTER HOUSING_PRICE_PROJECT.PUBLIC.TRAINTEST_SPLIT_TASK
AS 
CALL HOUSING_PRICE_PROJECT.ML_LAYER.PREPROCESSING_PROC();