-- CREATE STORAGE INTEGRATION FOR SNOWFLAKE **********************************************************************************************
CREATE STORAGE INTEGRATION IF NOT EXISTS HOUSEPRICE_S3_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = '{{AWS_ROLE_ARN}}'
STORAGE_ALLOWED_LOCATIONS = ('{{S3_BUCKET_URL}}');


-- CREATE THE EXTERNAL STAGE **********************************************************************************************
CREATE OR REPLACE STAGE HOUSING_PRICE_PROJECT.PUBLIC.HOUSEPRICE_STAGE
URL = '{{S3_BUCKET_URL}}'
STORAGE_INTEGRATION = HOUSEPRICE_S3_INTEGRATION; 